<a href="https://colab.research.google.com/github/testgithubit123/-THE-SPARKs-FOUNDATION-TASKS/blob/main/arithmetic_on_multiple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1=np.array([[1,2,3],[4,5,6],[8,9,0]])

In [3]:
arr2=np.array([[2,3,4],[5,6,7],[5,6,7]])

In [4]:
arr=arr1+arr2

In [5]:
arr

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [13, 15,  7]])

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [9]:
arr1[: ,: ]

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [11]:
arr1[:,:1]

array([[1],
       [4],
       [8]])

In [12]:
arr2

array([[2, 3, 4],
       [5, 6, 7],
       [5, 6, 7]])

In [13]:
arr2[1:,1:]

array([[6, 7],
       [6, 7]])