<a href="https://colab.research.google.com/github/testgithubit123/-THE-SPARKs-FOUNDATION-TASKS/blob/main/introduction_to_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

In [ ]:
lst = [[1,2,3],
 [3,4,5],
  [1,6,7]]

In [ ]:
type(lst)

list

In [ ]:
arr=np.array(lst)

In [ ]:
arr

array([[1, 2, 3],
       [3, 4, 5],
       [1, 6, 7]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((6,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.random.random((3,3))

array([[0.51080784, 0.0648308 , 0.70822927],
       [0.01292956, 0.79100284, 0.3481059 ],
       [0.81683709, 0.47902289, 0.58595893]])

In [ ]:
 if np.random.random()>.0:
  print("run the function")
 else:
  print("dont run") 



run the function


In [ ]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [ ]:
arr

array([[1, 2, 3],
       [3, 4, 5],
       [1, 6, 7]])

In [ ]:
arr=np.reshape(arr,(9,1))

In [ ]:
arr

array([[1],
       [2],
       [3],
       [3],
       [4],
       [5],
       [1],
       [6],
       [7]])

In [ ]:
arr.flatten()

array([1, 2, 3, 3, 4, 5, 1, 6, 7])